// lib/ports.ts
export const ports = [
  {
    id: 1,
    name: "Piraeus",
    country: "Greece",
    x: 52,
    y: 45,
    type: "headquarters",
    services: ["Agency", "Chandlers", "Repairs"],
  },
  {
    id: 2,
    name: "Singapore",
    country: "Singapore",
    x: 78,
    y: 65,
    type: "chandlers",
    services: ["Chandlers", "Agencies"],
  },
  {
    id: 3,
    name: "Rotterdam",
    country: "Netherlands",
    x: 48,
    y: 35,
    type: "chandlers",
    services: ["Chandlers"],
  },
  {
    id: 4,
    name: "Hamburg",
    country: "Germany",
    x: 50,
    y: 33,
    type: "repairs",
    services: ["Repairs"],
  },
  {
    id: 6,
    name: "Dubai",
    country: "UAE",
    x: 62,
    y: 52,
    type: "agency",
    services: ["Agencies", "Chandlers"],
  },
  {
    id: 7,
    name: "Hong Kong",
    country: "China",
    x: 82,
    y: 55,
    type: "chandlers",
    services: ["Agencies"],
  },
  {
    id: 9,
    name: "Los Angeles",
    country: "USA",
    x: 15,
    y: 48,
    type: "towage",
    services: ["Towage"],
  },
  {
    id: 10,
    name: "Panama",
    country: "Panama",
    x: 22,
    y: 58,
    type: "agency",
    services: ["Agencies", "Chandlers"],
  },
  {
    id: 11,
    name: "Shanghai",
    country: "China",
    x: 30,
    y: 70,
    type: "agency",
    services: ["Agencies", "Chandlers"],
  },
  {
    id: 12,
    name: "Busan",
    country: "South Korea",
    x: 40,
    y: 60,
    type: "chandlers",
    services: ["Chandlers", "Agencies"],
  },
  {
    id: 13,
    name: "Dakar",
    country: "Senegal",
    x: 35,
    y: 40,
    type: "agency",
    services: ["Agencies", "Chandlers"],
  },
  {
    id: 14,
    name: "Lagos",
    country: "Nigeria",
    x: 38,
    y: 45,
    type: "agency",
    services: ["Agencies"],
  },
  {
    id: 15,
    name: "Mombasa",
    country: "Kenya",
    x: 45,
    y: 55,
    type: "agency",
    services: ["Agencies", "Chandlers"],
  },
  {
    id: 16,
    name: "Port Louis",
    country: "Mauritius",
    x: 50,
    y: 60,
    type: "agency",
    services: ["Agencies"],
  },
  {
    id: 17,
    name: "Cape Town",
    country: "South Africa",
    x: 40,
    y: 70,
    type: "chandlers",
    services: ["Chandlers"],
  },
  {
    id: 18,
    name: "Santiago",
    country: "Chile",
    x: 10,
    y: 70,
    type: "towage",
    services: ["Towage"],
  },
  {
    id: 19,
    name: "Buenos Aires",
    country: "Argentina",
    x: 20,
    y: 75,
    type: "towage",
    services: ["Towage"],
  },
  {
    id: 20,
    name: "Lima",
    country: "Peru",
    x: 15,
    y: 65,
    type: "towage",
    services: ["Towage"],
  },
  {
    id: 21,
    name: "Guayaquil",
    country: "Ecuador",
    x: 18,
    y: 60,
    type: "towage",
    services: ["Towage"],
  },
  {
    id: 22,
    name: "Panama City",
    country: "Panama",
    x: 22,
    y: 58,
    type: "towage",
    services: ["Towage", "Chandlers"],
  },
  {
    id: 23,
    name: "Dos Bocas",
    country: "Mexico",
    x: 24,
    y: 60,
    type: "towage",
    services: ["Towage"],
  },
  {
    id: 24,
    name: "Houston",
    country: "USA",
    x: 30,
    y: 50,
    type: "chandlers",
    services: ["Chandlers", "Agencies"],
  },
  {
    id: 25,
    name: "Algeciras",
    country: "Spain",
    x: 45,
    y: 30,
    type: "agency",
    services: ["Agencies", "Chandlers"],
  },
  {
    id: 26,
    name: "Jakarta",
    country: "Indonesia",
    x: 75,
    y: 70,
    type: "agencies",
    services: ["Agencies"],
  },
] as const;
